# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: plugin.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import plugin_pb2 as plugin__pb2


class PluginRuntime(Protocol):
    async def health(self, request: plugin__pb2.HealthRequest, ctx: RequestContext) -> plugin__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def execute(self, request: plugin__pb2.ExecuteRequest, ctx: RequestContext) -> plugin__pb2.ExecuteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def execute_server_stream(self, request: plugin__pb2.ExecuteRequest, ctx: RequestContext) -> AsyncIterator[plugin__pb2.ExecuteChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def execute_client_stream(self, request: AsyncIterator[plugin__pb2.ExecuteRequest], ctx: RequestContext) -> plugin__pb2.ExecuteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def execute_bidi(self, request: AsyncIterator[plugin__pb2.ExecuteRequest], ctx: RequestContext) -> AsyncIterator[plugin__pb2.ExecuteChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PluginRuntimeASGIApplication(ConnectASGIApplication[PluginRuntime]):
    def __init__(self, service: PluginRuntime | AsyncGenerator[PluginRuntime], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/ragdoll.plugin.v1.PluginRuntime/Health": Endpoint.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.HealthRequest,
                        output=plugin__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/Execute": Endpoint.unary(
                    method=MethodInfo(
                        name="Execute",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteServerStream": Endpoint.server_stream(
                    method=MethodInfo(
                        name="ExecuteServerStream",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_server_stream,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteClientStream": Endpoint.client_stream(
                    method=MethodInfo(
                        name="ExecuteClientStream",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_client_stream,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteBidi": Endpoint.bidi_stream(
                    method=MethodInfo(
                        name="ExecuteBidi",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_bidi,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ragdoll.plugin.v1.PluginRuntime"


class PluginRuntimeClient(ConnectClient):
    async def health(
        self,
        request: plugin__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.HealthRequest,
                output=plugin__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def execute(
        self,
        request: plugin__pb2.ExecuteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.ExecuteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Execute",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_server_stream(
        self,
        request: plugin__pb2.ExecuteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[plugin__pb2.ExecuteChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteServerStream",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def execute_client_stream(
        self,
        request: AsyncIterator[plugin__pb2.ExecuteRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.ExecuteResponse:
        return await self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteClientStream",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_bidi(
        self,
        request: AsyncIterator[plugin__pb2.ExecuteRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[plugin__pb2.ExecuteChunk]:
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteBidi",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class PluginRuntimeSync(Protocol):
    def health(self, request: plugin__pb2.HealthRequest, ctx: RequestContext) -> plugin__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute(self, request: plugin__pb2.ExecuteRequest, ctx: RequestContext) -> plugin__pb2.ExecuteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute_server_stream(self, request: plugin__pb2.ExecuteRequest, ctx: RequestContext) -> Iterator[plugin__pb2.ExecuteChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute_client_stream(self, request: Iterator[plugin__pb2.ExecuteRequest], ctx: RequestContext) -> plugin__pb2.ExecuteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute_bidi(self, request: Iterator[plugin__pb2.ExecuteRequest], ctx: RequestContext) -> Iterator[plugin__pb2.ExecuteChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PluginRuntimeWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PluginRuntimeSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/ragdoll.plugin.v1.PluginRuntime/Health": EndpointSync.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.HealthRequest,
                        output=plugin__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/Execute": EndpointSync.unary(
                    method=MethodInfo(
                        name="Execute",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteServerStream": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="ExecuteServerStream",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_server_stream,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteClientStream": EndpointSync.client_stream(
                    method=MethodInfo(
                        name="ExecuteClientStream",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_client_stream,
                ),
                "/ragdoll.plugin.v1.PluginRuntime/ExecuteBidi": EndpointSync.bidi_stream(
                    method=MethodInfo(
                        name="ExecuteBidi",
                        service_name="ragdoll.plugin.v1.PluginRuntime",
                        input=plugin__pb2.ExecuteRequest,
                        output=plugin__pb2.ExecuteChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_bidi,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ragdoll.plugin.v1.PluginRuntime"


class PluginRuntimeClientSync(ConnectClientSync):
    def health(
        self,
        request: plugin__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.HealthRequest,
                output=plugin__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute(
        self,
        request: plugin__pb2.ExecuteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.ExecuteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Execute",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_server_stream(
        self,
        request: plugin__pb2.ExecuteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[plugin__pb2.ExecuteChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteServerStream",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_client_stream(
        self,
        request: Iterator[plugin__pb2.ExecuteRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> plugin__pb2.ExecuteResponse:
        return self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteClientStream",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_bidi(
        self,
        request: Iterator[plugin__pb2.ExecuteRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[plugin__pb2.ExecuteChunk]:
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="ExecuteBidi",
                service_name="ragdoll.plugin.v1.PluginRuntime",
                input=plugin__pb2.ExecuteRequest,
                output=plugin__pb2.ExecuteChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


