/**
 * Minimal dependency-free OpenSearch REST client.
 *
 * Deliberately uses `globalThis.fetch` rather than the official
 * `@opensearch-project/opensearch` package: the OpenSearch REST surface we
 * need (index admin, _bulk, _search, _delete_by_query) is tiny, a fetch shim
 * is trivially stubbable in offline unit tests, and it adds no install step to
 * a Docker-built monorepo whose deps are not present on dev machines.
 *
 * Auth is HTTP basic / an `Authorization` header, OR AWS SigV4 request signing
 * (`config.aws`) for AWS OpenSearch Serverless (`aoss`) and IAM-secured managed
 * domains (`es`). SigV4 stays dependency-free — the signer is `node:crypto` and
 * the credential chain is `fetch`/`node:fs` (see `./aws-sigv4.ts`).
 */

import {
  signSigV4,
  createAwsCredentialsProvider,
  type AwsSigV4Config,
  type AwsCredentialsProvider,
  type CredentialResolverDeps
} from "./aws-sigv4.ts";

export type { AwsSigV4Config };

export type FetchLike = (
  input: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
  }
) => Promise<{
  ok: boolean;
  status: number;
  text(): Promise<string>;
}>;

export interface OpenSearchAuth {
  /** HTTP basic auth (default for a security-enabled cluster). */
  username?: string;
  password?: string;
  /**
   * Raw value for an `Authorization` header (e.g. an API key). Takes
   * precedence over username/password when set.
   */
  authorization?: string;
}

export interface OpenSearchClientConfig {
  /** Base URL, e.g. `http://opensearch:9200`. */
  endpoint: string;
  auth?: OpenSearchAuth;
  /**
   * AWS SigV4 request signing — required for AWS OpenSearch Serverless
   * (`service: "aoss"`) and IAM-secured managed domains (`service: "es"`).
   * When set, every request is signed and `auth` is ignored. Credentials
   * resolve from `aws.accessKeyId`/`secretAccessKey`, then the standard AWS
   * env vars, then the ECS/EKS-Pod-Identity endpoint, then IRSA — or inject
   * `aws.credentialsProvider`.
   */
  aws?: AwsSigV4Config;
  /** Injected for tests; defaults to `globalThis.fetch`. */
  fetchImpl?: FetchLike;
  /** Injected for tests: the SigV4 credential-resolution environment. */
  awsResolverDeps?: CredentialResolverDeps;
}

export class OpenSearchError extends Error {
  status: number;
  body: unknown;
  constructor(status: number, message: string, body: unknown) {
    super(message);
    this.name = "OpenSearchError";
    this.status = status;
    this.body = body;
  }
}

export interface BulkDoc {
  /** Document id. Generated by OpenSearch when omitted. */
  id?: string;
  doc: Record<string, unknown>;
}

export interface SearchHit {
  id: string;
  score: number;
  source: Record<string, unknown>;
}

export class OpenSearchClient {
  private readonly endpoint: string;
  private readonly auth?: OpenSearchAuth;
  private readonly fetchImpl: FetchLike;
  private readonly sigv4?: {
    provider: AwsCredentialsProvider;
    region: string;
    service: string;
  };

  constructor(config: OpenSearchClientConfig) {
    if (!config.endpoint) {
      throw new OpenSearchError(0, "OpenSearchClient requires an endpoint", undefined);
    }
    this.endpoint = config.endpoint.replace(/\/+$/, "");
    this.auth = config.auth;
    const f = config.fetchImpl ?? (globalThis.fetch as unknown as FetchLike | undefined);
    if (!f) {
      throw new OpenSearchError(0, "no fetch implementation available", undefined);
    }
    this.fetchImpl = f;
    if (config.aws) {
      const region =
        config.aws.region ??
        config.awsResolverDeps?.env?.AWS_REGION ??
        process.env.AWS_REGION ??
        process.env.AWS_DEFAULT_REGION;
      if (!region) {
        throw new OpenSearchError(
          0,
          "OpenSearch AWS SigV4 requires a region (set aws.region or AWS_REGION)",
          undefined
        );
      }
      this.sigv4 = {
        provider: createAwsCredentialsProvider(config.aws, config.awsResolverDeps),
        region,
        // `es` = IAM-secured managed domain; `aoss` = OpenSearch Serverless.
        service: config.aws.service ?? "es"
      };
    }
  }

  /** AWS OpenSearch Serverless — the request-shape rules differ from a
   *  managed domain (`_bulk`/`_delete_by_query` reject the `refresh` param). */
  private get serverless(): boolean {
    return this.sigv4?.service === "aoss";
  }

  private headers(contentType = "application/json"): Record<string, string> {
    const headers: Record<string, string> = { "content-type": contentType };
    if (this.auth?.authorization) {
      headers.authorization = this.auth.authorization;
    } else if (this.auth?.username !== undefined) {
      const raw = `${this.auth.username}:${this.auth.password ?? ""}`;
      headers.authorization = `Basic ${Buffer.from(raw).toString("base64")}`;
    }
    return headers;
  }

  /** Low-level JSON request. `tolerate` status codes return the parsed body instead of throwing. */
  async request<T = unknown>(
    method: string,
    path: string,
    body?: unknown,
    opts: { tolerate?: number[]; ndjson?: boolean } = {}
  ): Promise<{ status: number; body: T }> {
    const url = `${this.endpoint}${path.startsWith("/") ? path : `/${path}`}`;
    const ndjson = opts.ndjson === true;
    const contentType = ndjson ? "application/x-ndjson" : "application/json";
    const bodyStr =
      body === undefined ? undefined : ndjson ? (body as string) : JSON.stringify(body);
    const headers = this.sigv4
      ? signSigV4({
          method,
          url,
          region: this.sigv4.region,
          service: this.sigv4.service,
          credentials: await this.sigv4.provider(),
          body: bodyStr,
          contentType
        }).headers
      : this.headers(contentType);
    const res = await this.fetchImpl(url, { method, headers, body: bodyStr });
    const text = await res.text();
    let parsed: unknown = undefined;
    if (text) {
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
    }
    if (!res.ok && !(opts.tolerate ?? []).includes(res.status)) {
      throw new OpenSearchError(
        res.status,
        `OpenSearch ${method} ${path} failed: HTTP ${res.status}`,
        parsed
      );
    }
    return { status: res.status, body: parsed as T };
  }

  async indexExists(index: string): Promise<boolean> {
    const { status } = await this.request("HEAD", `/${encodeURIComponent(index)}`, undefined, {
      tolerate: [404]
    });
    return status >= 200 && status < 300;
  }

  async createIndex(index: string, body: Record<string, unknown>): Promise<void> {
    await this.request("PUT", `/${encodeURIComponent(index)}`, body);
  }

  /** Create the index with `body` only if it does not already exist. */
  async ensureIndex(index: string, body: Record<string, unknown>): Promise<void> {
    if (await this.indexExists(index)) return;
    try {
      await this.createIndex(index, body);
    } catch (err) {
      // A racing writer may have created it between the check and the PUT.
      if (err instanceof OpenSearchError && err.status === 400 && (await this.indexExists(index))) {
        return;
      }
      throw err;
    }
  }

  async deleteIndex(index: string): Promise<void> {
    await this.request("DELETE", `/${encodeURIComponent(index)}`, undefined, { tolerate: [404] });
  }

  /**
   * Add fields to an existing index's mapping via PUT `_mapping`. Used to
   * graft a `knn_vector` field onto an index that was already created (often
   * by a sibling writer that ran first without a vector field). OpenSearch
   * accepts adding NEW fields freely; trying to change an existing field's
   * type 400s — that case is on the caller to detect.
   */
  async putMapping(index: string, properties: Record<string, unknown>): Promise<void> {
    await this.request("PUT", `/${encodeURIComponent(index)}/_mapping`, { properties });
  }

  /** Read the current property mapping for an index. Returns `{}` on 404. */
  async getMappingProperties(index: string): Promise<Record<string, unknown>> {
    try {
      const { body } = await this.request<Record<string, { mappings?: { properties?: Record<string, unknown> } }>>(
        "GET",
        `/${encodeURIComponent(index)}/_mapping`
      );
      const entry = body ? Object.values(body)[0] : undefined;
      return entry?.mappings?.properties ?? {};
    } catch (err) {
      if (err instanceof OpenSearchError && err.status === 404) return {};
      throw err;
    }
  }

  /**
   * Bulk-index documents. `refresh` makes them immediately searchable (handy
   * for tests/ingest). Internally splits the batch into chunks whose NDJSON
   * payload stays under ~5 MiB so OpenSearch's in-flight-request circuit
   * breaker doesn't trip on large corpora (the default heap fraction is
   * tight enough that a single ~50 MiB body 429s on a default-sized cluster).
   * Each chunk is retried once on a 429 after a short backoff before failing.
   */
  async bulkIndex(index: string, docs: BulkDoc[], refresh = false): Promise<{ indexed: number }> {
    if (docs.length === 0) return { indexed: 0 };
    const MAX_BYTES = 5 * 1024 * 1024;
    const lines: Array<{ action: string; doc: string; bytes: number }> = docs.map(({ id, doc }) => {
      const action = JSON.stringify({ index: { _index: index, ...(id ? { _id: id } : {}) } });
      const docStr = JSON.stringify(doc);
      return { action, doc: docStr, bytes: action.length + docStr.length + 2 };
    });
    let cursor = 0;
    while (cursor < lines.length) {
      let bytes = 0;
      let end = cursor;
      while (end < lines.length && (end === cursor || bytes + lines[end].bytes <= MAX_BYTES)) {
        bytes += lines[end].bytes;
        end += 1;
      }
      const chunk = lines.slice(cursor, end);
      const ndjson = chunk.map((c) => `${c.action}\n${c.doc}`).join("\n") + "\n";
      let body: { errors?: boolean; items?: unknown[] } | undefined;
      let attempt = 0;
      while (true) {
        try {
          const resp = await this.request<{ errors?: boolean; items?: unknown[] }>(
            "POST",
            // AWS OpenSearch Serverless (aoss) rejects the `refresh` param on
            // _bulk with a 400 — it is near-real-time and refreshes on its own.
            // Drop it there; honor it everywhere else.
            `/_bulk${refresh && !this.serverless ? "?refresh=true" : ""}`,
            ndjson,
            { ndjson: true }
          );
          body = resp.body;
          break;
        } catch (err) {
          // Retry once on 429 (circuit breaker / queue full) with a small
          // delay; rethrow anything else, and the second 429 too.
          const status = (err as { status?: number } | undefined)?.status;
          if (status === 429 && attempt === 0) {
            attempt += 1;
            await new Promise((resolve) => setTimeout(resolve, 500));
            continue;
          }
          throw err;
        }
      }
      cursor = end;
      if (body?.errors) {
      // Surface the first failed item's reason so the operator can act on
      // it instead of staring at a generic "bulk index reported item
      // errors". OpenSearch's response is an array of per-op shells; we
      // walk it for the first one carrying a `.error` and pluck `type`
      // and `reason` for the message.
      const items = Array.isArray(body.items) ? body.items : [];
      let firstFailure: { type?: string; reason?: string } | undefined;
      let failedCount = 0;
      for (const item of items) {
        if (!item || typeof item !== "object") continue;
        for (const op of Object.values(item as Record<string, unknown>)) {
          const err = (op as { error?: unknown } | undefined)?.error;
          if (err && typeof err === "object") {
            failedCount += 1;
            if (!firstFailure) {
              firstFailure = err as { type?: string; reason?: string };
            }
          }
        }
      }
      const summary = firstFailure
        ? `${firstFailure.type ?? "unknown"}: ${firstFailure.reason ?? "(no reason)"}`
        : "(no per-item detail)";
      throw new OpenSearchError(
        207,
        `OpenSearch bulk index reported ${failedCount} failed item${
          failedCount === 1 ? "" : "s"
        } — first failure: ${summary}`,
        body
      );
      }
    }
    return { indexed: docs.length };
  }

  async search(
    index: string,
    query: Record<string, unknown>
  ): Promise<{ total: number; hits: SearchHit[] }> {
    // "Search an index that doesn't exist" returns zero hits — symmetric
    // with deleteByQuery's tolerate posture. Retrieval pipelines pointed
    // at a fresh dataset (before any ingest has created the index) hit
    // this. A real 5xx still throws; only the 404 "index_not_found_exception"
    // is treated as an empty result.
    const { status, body } = await this.request<{
      hits?: {
        total?: { value?: number } | number;
        hits?: Array<{ _id: string; _score: number | null; _source?: Record<string, unknown> }>;
      };
    }>("POST", `/${encodeURIComponent(index)}/_search`, query, { tolerate: [404] });
    if (status === 404) return { total: 0, hits: [] };
    const rawTotal = body?.hits?.total;
    const total =
      typeof rawTotal === "number" ? rawTotal : (rawTotal?.value ?? body?.hits?.hits?.length ?? 0);
    const hits = (body?.hits?.hits ?? []).map((hit) => ({
      id: hit._id,
      score: hit._score ?? 0,
      source: hit._source ?? {}
    }));
    return { total, hits };
  }

  async deleteByQuery(index: string, query: Record<string, unknown>): Promise<void> {
    // aoss auto-refreshes and rejects the `refresh` param; keep conflicts=proceed.
    const params = this.serverless ? "conflicts=proceed" : "refresh=true&conflicts=proceed";
    await this.request(
      "POST",
      `/${encodeURIComponent(index)}/_delete_by_query?${params}`,
      { query },
      { tolerate: [404] }
    );
  }
}

/** Build a client from loosely-typed plugin config + secrets. Returns undefined when no endpoint is set. */
export function createOpenSearchClient(opts: {
  endpoint?: string;
  username?: string;
  password?: string;
  authorization?: string;
  /** AWS SigV4 signing (AWS OpenSearch Serverless / IAM-secured domains).
   *  When set, takes precedence over username/password/authorization. */
  aws?: AwsSigV4Config;
  fetchImpl?: FetchLike;
}): OpenSearchClient | undefined {
  const endpoint = opts.endpoint ?? process.env.OPENSEARCH_URL;
  if (!endpoint) return undefined;
  const auth: OpenSearchAuth | undefined =
    !opts.aws && (opts.authorization || opts.username !== undefined)
      ? {
          authorization: opts.authorization,
          username: opts.username,
          password: opts.password
        }
      : undefined;
  return new OpenSearchClient({ endpoint, auth, aws: opts.aws, fetchImpl: opts.fetchImpl });
}

/**
 * JSON-schema `properties` fragment for the AWS SigV4 secret-ref fields
 * {@link awsSigV4FromSecrets} reads. Spread into a plugin's `secretsSchema` so
 * the Builder renders inputs for them — the field NAMES here must match what
 * the mapper below reads. Region/service flow through the same `secrets` block
 * as the credentials (that's how the plugin receives them), hence `secret-ref`.
 */
export const AWS_SIGV4_SECRET_FIELDS = {
  awsRegion: {
    type: "string",
    format: "secret-ref",
    description: "AWS region (e.g. us-east-1). Setting this enables SigV4 signing."
  },
  awsService: {
    type: "string",
    format: "secret-ref",
    description: "'aoss' for OpenSearch Serverless, 'es' for an IAM-secured managed domain (default 'es')."
  },
  awsAccessKeyId: {
    type: "string",
    format: "secret-ref",
    description: "AWS access key id. Optional — omit to use the pod's IAM role (IRSA / Pod Identity)."
  },
  awsSecretAccessKey: {
    type: "string",
    format: "secret-ref",
    description: "AWS secret access key. Optional — pairs with awsAccessKeyId."
  },
  awsSessionToken: {
    type: "string",
    format: "secret-ref",
    description: "AWS session token for temporary credentials. Optional."
  }
} as const;

/**
 * Map a connection's flat secret map to an {@link AwsSigV4Config}, or undefined
 * when SigV4 isn't requested. Enabled by any of `awsSigv4`, `awsRegion`, or
 * `awsService` being present. Credential fields are optional — omit them to
 * fall through to the env / instance-role chain (IRSA, Pod Identity, …).
 */
export function awsSigV4FromSecrets(
  secrets: Record<string, string | undefined>
): AwsSigV4Config | undefined {
  const enabled =
    secrets.awsSigv4 === "true" ||
    Boolean(secrets.awsRegion) ||
    Boolean(secrets.awsService);
  if (!enabled) return undefined;
  return {
    region: secrets.awsRegion,
    service: secrets.awsService,
    accessKeyId: secrets.awsAccessKeyId,
    secretAccessKey: secrets.awsSecretAccessKey,
    sessionToken: secrets.awsSessionToken
  };
}

/**
 * Same as {@link awsSigV4FromSecrets} but reads from a connection's `options`
 * (config) blob — so an operator can enable SigV4 once on the CONNECTION
 * (`awsRegion` + `awsService: aoss`) instead of on every node's secrets. Values
 * are coerced to strings; non-string entries are ignored.
 */
export function awsSigV4FromConnectionOptions(
  options: Record<string, unknown> | undefined
): AwsSigV4Config | undefined {
  if (!options) return undefined;
  const str = (k: string): string | undefined =>
    typeof options[k] === "string" ? (options[k] as string) : undefined;
  return awsSigV4FromSecrets({
    awsSigv4: options.awsSigv4 === true ? "true" : str("awsSigv4"),
    awsRegion: str("awsRegion"),
    awsService: str("awsService"),
    awsAccessKeyId: str("awsAccessKeyId"),
    awsSecretAccessKey: str("awsSecretAccessKey"),
    awsSessionToken: str("awsSessionToken")
  });
}

/**
 * Merge SigV4 configs field-by-field, later sources overriding earlier ones for
 * fields they actually set. Returns undefined only when EVERY source is absent
 * (SigV4 stays off). Used to layer node secrets over the connection's config.
 */
export function mergeAwsSigV4(
  ...configs: Array<AwsSigV4Config | undefined>
): AwsSigV4Config | undefined {
  let out: AwsSigV4Config | undefined;
  for (const c of configs) {
    if (!c) continue;
    out = out ?? {};
    for (const [k, v] of Object.entries(c)) {
      if (v !== undefined) (out as Record<string, unknown>)[k] = v;
    }
  }
  return out;
}
