/**
 * Minimal dependency-free OpenSearch REST client.
 *
 * Deliberately uses `globalThis.fetch` rather than the official
 * `@opensearch-project/opensearch` package: the OpenSearch REST surface we
 * need (index admin, _bulk, _search, _delete_by_query) is tiny, a fetch shim
 * is trivially stubbable in offline unit tests, and it adds no install step to
 * a Docker-built monorepo whose deps are not present on dev machines.
 */

export type FetchLike = (
  input: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
  }
) => Promise<{
  ok: boolean;
  status: number;
  text(): Promise<string>;
}>;

export interface OpenSearchAuth {
  /** HTTP basic auth (default for a security-enabled cluster). */
  username?: string;
  password?: string;
  /**
   * Raw value for an `Authorization` header (e.g. an API key). Takes
   * precedence over username/password when set.
   */
  authorization?: string;
}

export interface OpenSearchClientConfig {
  /** Base URL, e.g. `http://opensearch:9200`. */
  endpoint: string;
  auth?: OpenSearchAuth;
  /** Injected for tests; defaults to `globalThis.fetch`. */
  fetchImpl?: FetchLike;
}

export class OpenSearchError extends Error {
  status: number;
  body: unknown;
  constructor(status: number, message: string, body: unknown) {
    super(message);
    this.name = "OpenSearchError";
    this.status = status;
    this.body = body;
  }
}

export interface BulkDoc {
  /** Document id. Generated by OpenSearch when omitted. */
  id?: string;
  doc: Record<string, unknown>;
}

export interface SearchHit {
  id: string;
  score: number;
  source: Record<string, unknown>;
}

export class OpenSearchClient {
  private readonly endpoint: string;
  private readonly auth?: OpenSearchAuth;
  private readonly fetchImpl: FetchLike;

  constructor(config: OpenSearchClientConfig) {
    if (!config.endpoint) {
      throw new OpenSearchError(0, "OpenSearchClient requires an endpoint", undefined);
    }
    this.endpoint = config.endpoint.replace(/\/+$/, "");
    this.auth = config.auth;
    const f = config.fetchImpl ?? (globalThis.fetch as unknown as FetchLike | undefined);
    if (!f) {
      throw new OpenSearchError(0, "no fetch implementation available", undefined);
    }
    this.fetchImpl = f;
  }

  private headers(contentType = "application/json"): Record<string, string> {
    const headers: Record<string, string> = { "content-type": contentType };
    if (this.auth?.authorization) {
      headers.authorization = this.auth.authorization;
    } else if (this.auth?.username !== undefined) {
      const raw = `${this.auth.username}:${this.auth.password ?? ""}`;
      headers.authorization = `Basic ${Buffer.from(raw).toString("base64")}`;
    }
    return headers;
  }

  /** Low-level JSON request. `tolerate` status codes return the parsed body instead of throwing. */
  async request<T = unknown>(
    method: string,
    path: string,
    body?: unknown,
    opts: { tolerate?: number[]; ndjson?: boolean } = {}
  ): Promise<{ status: number; body: T }> {
    const url = `${this.endpoint}${path.startsWith("/") ? path : `/${path}`}`;
    const ndjson = opts.ndjson === true;
    const res = await this.fetchImpl(url, {
      method,
      headers: this.headers(ndjson ? "application/x-ndjson" : "application/json"),
      body:
        body === undefined
          ? undefined
          : ndjson
            ? (body as string)
            : JSON.stringify(body)
    });
    const text = await res.text();
    let parsed: unknown = undefined;
    if (text) {
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
    }
    if (!res.ok && !(opts.tolerate ?? []).includes(res.status)) {
      throw new OpenSearchError(
        res.status,
        `OpenSearch ${method} ${path} failed: HTTP ${res.status}`,
        parsed
      );
    }
    return { status: res.status, body: parsed as T };
  }

  async indexExists(index: string): Promise<boolean> {
    const { status } = await this.request("HEAD", `/${encodeURIComponent(index)}`, undefined, {
      tolerate: [404]
    });
    return status >= 200 && status < 300;
  }

  async createIndex(index: string, body: Record<string, unknown>): Promise<void> {
    await this.request("PUT", `/${encodeURIComponent(index)}`, body);
  }

  /** Create the index with `body` only if it does not already exist. */
  async ensureIndex(index: string, body: Record<string, unknown>): Promise<void> {
    if (await this.indexExists(index)) return;
    try {
      await this.createIndex(index, body);
    } catch (err) {
      // A racing writer may have created it between the check and the PUT.
      if (err instanceof OpenSearchError && err.status === 400 && (await this.indexExists(index))) {
        return;
      }
      throw err;
    }
  }

  async deleteIndex(index: string): Promise<void> {
    await this.request("DELETE", `/${encodeURIComponent(index)}`, undefined, { tolerate: [404] });
  }

  /** Bulk-index documents. `refresh` makes them immediately searchable (handy for tests/ingest). */
  async bulkIndex(index: string, docs: BulkDoc[], refresh = false): Promise<{ indexed: number }> {
    if (docs.length === 0) return { indexed: 0 };
    const lines: string[] = [];
    for (const { id, doc } of docs) {
      lines.push(JSON.stringify({ index: { _index: index, ...(id ? { _id: id } : {}) } }));
      lines.push(JSON.stringify(doc));
    }
    const ndjson = `${lines.join("\n")}\n`;
    const { body } = await this.request<{ errors?: boolean; items?: unknown[] }>(
      "POST",
      `/_bulk${refresh ? "?refresh=true" : ""}`,
      ndjson,
      { ndjson: true }
    );
    if (body?.errors) {
      throw new OpenSearchError(207, "OpenSearch bulk index reported item errors", body);
    }
    return { indexed: docs.length };
  }

  async search(
    index: string,
    query: Record<string, unknown>
  ): Promise<{ total: number; hits: SearchHit[] }> {
    const { body } = await this.request<{
      hits?: {
        total?: { value?: number } | number;
        hits?: Array<{ _id: string; _score: number | null; _source?: Record<string, unknown> }>;
      };
    }>("POST", `/${encodeURIComponent(index)}/_search`, query);
    const rawTotal = body?.hits?.total;
    const total =
      typeof rawTotal === "number" ? rawTotal : (rawTotal?.value ?? body?.hits?.hits?.length ?? 0);
    const hits = (body?.hits?.hits ?? []).map((hit) => ({
      id: hit._id,
      score: hit._score ?? 0,
      source: hit._source ?? {}
    }));
    return { total, hits };
  }

  async deleteByQuery(index: string, query: Record<string, unknown>): Promise<void> {
    await this.request(
      "POST",
      `/${encodeURIComponent(index)}/_delete_by_query?refresh=true&conflicts=proceed`,
      { query },
      { tolerate: [404] }
    );
  }
}

/** Build a client from loosely-typed plugin config + secrets. Returns undefined when no endpoint is set. */
export function createOpenSearchClient(opts: {
  endpoint?: string;
  username?: string;
  password?: string;
  authorization?: string;
  fetchImpl?: FetchLike;
}): OpenSearchClient | undefined {
  const endpoint = opts.endpoint ?? process.env.OPENSEARCH_URL;
  if (!endpoint) return undefined;
  const auth: OpenSearchAuth | undefined =
    opts.authorization || opts.username !== undefined
      ? {
          authorization: opts.authorization,
          username: opts.username,
          password: opts.password
        }
      : undefined;
  return new OpenSearchClient({ endpoint, auth, fetchImpl: opts.fetchImpl });
}
