apiVersion: rag-platform/v1
kind: Pipeline
metadata:
  name: query-only
spec:
  nodes:
  - id: input
    type: input
    ui:
      position:
        x: 1.091796875
        y: 40
  - id: prompt
    plugin:
      category: prompt_template
      id: basic_rag_prompt
      version: 1.0.0
    ui:
      position:
        x: 459.57373046875
        y: 40
  - id: llm
    plugin:
      category: llm
      id: provider_chat
      version: 1.0.0
    config:
      provider: "${config.llm.provider}"
      model: "${config.llm.model}"
    secrets:
      apiKey:
        scope: tenant
        key: llm.api_key
    ui:
      position:
        x: 918.72705078125
        y: 40
  - id: parse
    plugin:
      category: output_parser
      id: json_output_parser
      version: 1.0.0
    ui:
      position:
        x: 1379.3037109375
        y: 40
  - id: output
    type: output
    ui:
      position:
        x: 1841.3037109375
        y: 40
  edges:
  - from: input
    to: prompt
    fromPort: question
    toPort: question
  - from: prompt
    to: llm
    fromPort: messages
    toPort: messages
  - from: llm
    to: parse
    fromPort: text
    toPort: text
  - from: parse
    to: output
