apiVersion: rag-platform/v1
kind: Pipeline
metadata:
  name: support-ingestion
  labels:
    domain: support
    mode: ingestion
  stages:
  - id: s_auto_1
    label: Stage 1
  - id: s_auto_2
    label: Stage 2
  - id: s_auto_3
    label: Stage 3
  - id: s_auto_4
    label: Stage 4
  - id: s_auto_5
    label: Stage 5
  - id: s_auto_6
    label: Stage 6
spec:
  nodes:
  - id: input
    type: input
    ui:
      position:
        x: -1.8408203125
        y: 40
      stageId: s_auto_1
  - id: load
    plugin:
      category: loader
      id: file_document_loader
      version: 1.0.0
    ui:
      position:
        x: 453.6171875
        y: 40
      stageId: s_auto_2
  - id: chunk
    plugin:
      category: chunker
      id: basic_text_chunker
      version: 1.0.0
    config:
      chunkSize: "${config.chunking.chunk_size}"
      overlap: 100
    ui:
      position:
        x: 909.018798828125
        y: 40
      stageId: s_auto_3
  - id: embed
    plugin:
      category: embedder
      id: provider_embeddings
      version: 1.0.0
    config:
      provider: "${config.embedding.provider}"
      model: "${config.embedding.model}"
    ui:
      position:
        x: 1366.055908203125
        y: 40
      stageId: s_auto_4
  - id: write
    plugin:
      category: vector_store
      id: qdrant_vector_store
      version: 1.0.0
    dataset:
      slug: support-ingestion
      alias: stable
    config:
      isolationMode: "${config.vector.isolation.mode}"
    ui:
      position:
        x: 1825.574462890625
        y: 40
      stageId: s_auto_5
  - id: output
    type: output
    ui:
      position:
        x: 2287.574462890625
        y: 40
      stageId: s_auto_6
  edges:
  - from: input
    to: load
  - from: load
    to: chunk
  - from: chunk
    to: embed
    fromPort: chunks
    toPort: chunks
  - from: chunk
    to: write
    fromPort: chunks
    toPort: chunks
  - from: embed
    to: write
    fromPort: vectors
    toPort: vectors
  - from: write
    to: output
