{{- if .Values.pythonPlugins.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-plugins
  labels:
    app: {{ .Release.Name }}-python-plugins
    {{- include "ragdoll.commonLabels" . | nindent 4 }}
  {{- with (include "ragdoll.commonAnnotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}-python-plugins
  ports:
    - name: http
      port: {{ .Values.pythonPlugins.port }}
      targetPort: {{ .Values.pythonPlugins.port }}
{{- end }}
