{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ragdoll.serviceAccountName" . }}
  labels:
    {{- include "ragdoll.commonLabels" . | nindent 4 }}
  {{- with (include "ragdoll.commonAnnotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
