apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragdoll-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: ragdoll-web
  template:
    metadata:
      labels:
        app: ragdoll-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}-web:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
