/**
 * Tone-matched composition plugins.
 *
 *   - `tone_profile_build` runs over a sender's outgoing messages and
 *     produces (a) a curated exemplar set ready to be written to a
 *     Ragdoll dataset by a downstream `dataset_upsert`, and (b) a
 *     short static style guide generated by one provider call over a
 *     representative sample. Batch only — building a tone profile is
 *     an offline preparation step, not a hot-path operation.
 *
 *   - `compose_with_style` is the synchronous reply composer:
 *     style guide in the system prompt, retrieved exemplars as
 *     few-shot, thread + intent context as the user prompt. Defaults
 *     to a stronger model (Sonnet-class) since this is the
 *     user-visible output. Slowest sync plugin — operators relying
 *     on tight latency should test with their target provider.
 */

import type { InProcessPlugin } from "../../../../packages/plugin-sdk/src/index.ts";
import { buildProviderRegistry, resolveChatModel } from "../helpers.ts";

const PROVIDER_ENUM = ["openai", "anthropic", "ollama"];
const PROVIDER_SECRETS_SCHEMA = {
  type: "object",
  properties: {
    apiKey: { type: "string", format: "secret-ref", description: "Provider API key (when required)." }
  },
  additionalProperties: false
};

interface MessageLike {
  text?: string;
  body?: string;
  [field: string]: unknown;
}

/**
 * Curate exemplars from a batch of outgoing messages. Pure, deterministic,
 * unit-testable. Heuristics:
 *   - drop messages shorter than `minChars` (one-liners aren't tone-bearing).
 *   - drop messages longer than `maxChars` (mega-replies aren't useful few-shot).
 *   - dedupe near-identical text (collapse hash by length-bucket + first 64 chars).
 *   - sort by a "tone signal" score: punctuation variety + word variety +
 *     length-in-range. Keep the top `sampleSize`.
 */
export function curateExemplars(args: {
  messages: MessageLike[];
  textField: string;
  sampleSize: number;
  minChars?: number;
  maxChars?: number;
}): MessageLike[] {
  const minChars = args.minChars ?? 60;
  const maxChars = args.maxChars ?? 800;
  const seen = new Set<string>();
  const scored: Array<{ msg: MessageLike; text: string; score: number }> = [];
  for (const msg of args.messages) {
    const raw = msg[args.textField] ?? msg.text ?? msg.body;
    if (typeof raw !== "string") continue;
    const text = raw.trim();
    if (text.length < minChars || text.length > maxChars) continue;
    const key = `${Math.floor(text.length / 32)}:${text.slice(0, 64).toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    scored.push({ msg, text, score: toneSignalScore(text) });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, args.sampleSize).map(({ msg, text }) => ({ ...msg, text }));
}

function toneSignalScore(text: string): number {
  const lengthScore = 1 - Math.abs(text.length - 300) / 800;
  const punctVariety = new Set(text.match(/[.,;:!?\-—]/g) ?? []).size / 6;
  const wordVariety = uniqueLowercaseWords(text) / Math.max(1, text.split(/\s+/).length);
  return Math.max(0, lengthScore) * 0.4 + punctVariety * 0.3 + wordVariety * 0.3;
}

function uniqueLowercaseWords(text: string): number {
  return new Set(text.toLowerCase().split(/\s+/)).size;
}

// ---------------------------------------------------------------------------
// tone_profile_build
// ---------------------------------------------------------------------------

export const toneProfileBuildPlugin: InProcessPlugin = {
  manifest: {
    id: "tone_profile_build",
    name: "Tone Profile Build",
    version: "1.0.0",
    category: "transformer",
    description:
      "Builds a sender's tone profile from their outgoing messages: a curated exemplar set ready for a Ragdoll dataset, plus a short static style guide generated by one provider call. Batch only.",
    configSchema: {
      type: "object",
      properties: {
        provider: { type: "string", enum: PROVIDER_ENUM, default: "anthropic" },
        model: {
          type: "string",
          default: "claude-3-5-sonnet-latest",
          description: "Style-guide model. Defaults to a stronger model since this is an offline build step."
        },
        textField: { type: "string", default: "text" },
        sampleSize: {
          type: "integer",
          default: 40,
          description: "Number of curated exemplars to keep."
        },
        minChars: { type: "integer", default: 60 },
        maxChars: { type: "integer", default: 800 },
        styleGuideTokens: {
          type: "integer",
          default: 800,
          description: "Max tokens for the generated style guide."
        },
        systemPrompt: {
          type: "string",
          default:
            "You read a small sample of one author's written messages and produce a concise, actionable style guide describing how they write. Focus on diction, sentence length, formality register, recurring openings/closings, and any signature mannerisms. Keep it under one page."
        }
      },
      additionalProperties: false
    },
    secretsSchema: PROVIDER_SECRETS_SCHEMA,
    inputPorts: [
      { name: "messages", required: true, description: "The sender's outgoing messages." }
    ],
    outputPorts: [
      { name: "exemplars", description: "Curated exemplars ready to be wired into a `dataset_upsert`." },
      { name: "styleGuide", description: "The generated style guide as a single string." },
      { name: "sampleCount", description: "Number of messages the curator kept." }
    ],
    capabilities: ["transform", "llm"],
    ui: {
      icon: "user",
      color: "#db2777",
      formHints: {
        provider: { widget: "select" },
        systemPrompt: { widget: "textarea", rows: 4 },
        sampleSize: { widget: "number", min: 1, step: 1 },
        minChars: { widget: "number", min: 0, step: 10 },
        maxChars: { widget: "number", min: 0, step: 50 }
      }
    }
  },
  async execute(input) {
    const { inputs, config, secrets, context } = input;
    const messages = inputs.messages ?? inputs.records ?? inputs.documents;
    if (!Array.isArray(messages)) {
      throw new Error("tone_profile_build: `inputs.messages` must be an array.");
    }
    const exemplars = curateExemplars({
      messages: messages as MessageLike[],
      textField: String(config.textField ?? "text"),
      sampleSize: Math.max(1, Number(config.sampleSize ?? 40)),
      minChars: Number(config.minChars ?? 60),
      maxChars: Number(config.maxChars ?? 800)
    });
    if (exemplars.length === 0) {
      return { outputs: { exemplars: [], styleGuide: "", sampleCount: 0 } };
    }
    const providers = buildProviderRegistry();
    const { providerId, model, baseUrl } = resolveChatModel({
      config,
      resolvedValues: context.resolvedConfig.values,
      defaultProvider: "anthropic",
      defaultModel: "claude-3-5-sonnet-latest"
    });
    const provider = providers.require(providerId);
    const sample = exemplars
      .slice(0, Math.min(20, exemplars.length))
      .map((e, i) => `<sample n="${i + 1}">\n${String(e.text ?? "")}\n</sample>`)
      .join("\n\n");
    const response = await provider.chat({
      tenantId: context.tenantId,
      model,
      messages: [
        { role: "system", content: String(config.systemPrompt ?? "") },
        { role: "user", content: sample }
      ],
      temperature: 0.2,
      maxTokens: Number(config.styleGuideTokens ?? 800),
      apiKey: secrets.apiKey,
      baseUrl
    });
    return {
      outputs: {
        exemplars,
        styleGuide: (response.text ?? "").trim(),
        sampleCount: exemplars.length
      },
      usage: { provider: providerId, model }
    };
  }
};

// ---------------------------------------------------------------------------
// compose_with_style
// ---------------------------------------------------------------------------

export const composeWithStylePlugin: InProcessPlugin = {
  manifest: {
    id: "compose_with_style",
    name: "Compose with Style",
    version: "1.0.0",
    category: "llm",
    description:
      "Composes a reply in the sender's tone: static style guide in the system prompt + retrieved exemplars as few-shot + thread / intent context. Defaults to a stronger model since this is the user-visible output.",
    configSchema: {
      type: "object",
      properties: {
        provider: { type: "string", enum: PROVIDER_ENUM, default: "anthropic" },
        model: { type: "string", default: "claude-3-5-sonnet-latest" },
        styleGuideField: {
          type: "string",
          default: "styleGuide",
          description: "Input field holding the static style guide string."
        },
        exemplarsField: {
          type: "string",
          default: "exemplars",
          description: "Input field holding the retrieved exemplars (array of { text } objects)."
        },
        threadField: {
          type: "string",
          default: "thread",
          description: "Input field holding the conversation context to reply to."
        },
        intentField: {
          type: "string",
          default: "intent",
          description: "Optional input field carrying a brief user intent string."
        },
        systemPromptPrefix: {
          type: "string",
          default:
            "You are drafting a reply on behalf of a specific person. Match their voice closely, using the style guide below. Use the exemplars as reference for tone, not for content. Keep the reply focused on the user's intent and the thread context."
        },
        maxTokens: { type: "integer", default: 800 },
        temperature: { type: "number", default: 0.5 },
        markUncertain: {
          type: "boolean",
          default: true,
          description: "When true and the exemplar set is small (<5), the draft is prefixed with `[low-confidence draft]`."
        }
      },
      additionalProperties: false
    },
    secretsSchema: PROVIDER_SECRETS_SCHEMA,
    inputPorts: [
      { name: "styleGuide", required: true },
      { name: "exemplars" },
      { name: "thread", required: true },
      { name: "intent" }
    ],
    outputPorts: [
      { name: "draft", description: "The composed reply." },
      { name: "exemplarsUsed", description: "Echo of the exemplar references included in the prompt." },
      { name: "uncertain", description: "True when the draft is flagged low-confidence." }
    ],
    capabilities: ["llm", "synchronous"],
    ui: {
      icon: "edit",
      color: "#db2777",
      formHints: {
        provider: { widget: "select" },
        systemPromptPrefix: { widget: "textarea", rows: 4 },
        temperature: { widget: "range", min: 0, max: 2, step: 0.1 },
        markUncertain: { widget: "checkbox" }
      }
    }
  },
  async execute(input) {
    const { inputs, config, secrets, context } = input;
    const styleGuide = String(
      inputs[String(config.styleGuideField ?? "styleGuide")] ?? inputs.styleGuide ?? ""
    );
    const exemplarsRaw = inputs[String(config.exemplarsField ?? "exemplars")] ?? inputs.exemplars;
    const exemplars: Array<{ text?: string }> = Array.isArray(exemplarsRaw)
      ? (exemplarsRaw as Array<{ text?: string }>)
      : [];
    const thread = String(inputs[String(config.threadField ?? "thread")] ?? inputs.thread ?? "");
    const intent = String(inputs[String(config.intentField ?? "intent")] ?? inputs.intent ?? "");
    if (!styleGuide || !thread) {
      throw new Error("compose_with_style: both `styleGuide` and `thread` are required.");
    }
    const providers = buildProviderRegistry();
    const { providerId, model, baseUrl } = resolveChatModel({
      config,
      resolvedValues: context.resolvedConfig.values,
      defaultProvider: "anthropic",
      defaultModel: "claude-3-5-sonnet-latest"
    });
    const provider = providers.require(providerId);

    const exemplarBlock = exemplars
      .slice(0, 8)
      .map((e, i) => `<exemplar n="${i + 1}">\n${String(e.text ?? "")}\n</exemplar>`)
      .join("\n\n");
    const systemPrompt = [
      String(config.systemPromptPrefix ?? ""),
      "",
      "<style-guide>",
      styleGuide,
      "</style-guide>",
      "",
      exemplarBlock ? "<exemplars>\n" + exemplarBlock + "\n</exemplars>" : ""
    ]
      .filter(Boolean)
      .join("\n");
    const userPrompt = [
      intent ? `Intent: ${intent}\n` : "",
      "Thread:\n",
      thread,
      "\n\nWrite the reply now. Output ONLY the body of the reply — no greeting framing, no commentary."
    ].join("");

    const response = await provider.chat({
      tenantId: context.tenantId,
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: Number(config.temperature ?? 0.5),
      maxTokens: Number(config.maxTokens ?? 800),
      apiKey: secrets.apiKey,
      baseUrl
    });

    const uncertain = config.markUncertain !== false && exemplars.length < 5;
    let draft = (response.text ?? "").trim();
    if (uncertain) draft = `[low-confidence draft]\n${draft}`;

    return {
      outputs: {
        draft,
        exemplarsUsed: exemplars.slice(0, 8).map((e, i) => ({ index: i, text: String(e.text ?? "") })),
        uncertain
      },
      usage: { provider: providerId, model }
    };
  }
};
