// RAGdoll external-plugin wire contract.
//
// One service, five methods covering the four RPC kinds plus a Health probe.
// Served by every external plugin (Node or Python) via connect-rpc, which
// exposes the SAME handler over Connect HTTP/JSON, gRPC-Web, and native gRPC
// from one process. Clients pick the protocol best suited to the runtime
// (gRPC for backpressure-heavy streaming, Connect HTTP for browser/curl).
//
// google.protobuf.Struct carries the dynamic per-plugin payload because the
// shape varies per plugin and is validated against the plugin's
// `inputSchema` / `outputSchema` (zod) at the runtime boundary.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file plugin.proto (package ragdoll.plugin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file plugin.proto.
 */
export const file_plugin: GenFile = /*@__PURE__*/
  fileDesc("CgxwbHVnaW4ucHJvdG8SEXJhZ2RvbGwucGx1Z2luLnYxIg8KDUhlYWx0aFJlcXVlc3QiPgoOSGVhbHRoUmVzcG9uc2USCgoCb2sYASABKAgSDwoHcGx1Z2lucxgCIAMoCRIPCgdtZXNzYWdlGAMgASgJIrkCCg5FeGVjdXRlUmVxdWVzdBIOCgZwbHVnaW4YASABKAkSDwoHdmVyc2lvbhgCIAEoCRIPCgdub2RlX2lkGAMgASgJEhEKCXRlbmFudF9pZBgEIAEoCRITCgtlbnZpcm9ubWVudBgFIAEoCRISCgpyZXF1ZXN0X2lkGAYgASgJEicKBmNvbmZpZxgHIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QSJwoGaW5wdXRzGAggASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBIoCgdkYXRhc2V0GAkgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBIoCgdzZWNyZXRzGAogASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBITCgtkZWFkbGluZV9tcxgLIAEoBSK/AQoPRXhlY3V0ZVJlc3BvbnNlEigKB291dHB1dHMYASABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EikKCG1ldGFkYXRhGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBInCgV1c2FnZRgDIAEoCzIYLnJhZ2RvbGwucGx1Z2luLnYxLlVzYWdlEi4KCWFydGlmYWN0cxgEIAMoCzIbLnJhZ2RvbGwucGx1Z2luLnYxLkFydGlmYWN0IpoBCgxFeGVjdXRlQ2h1bmsSDwoFdG9rZW4YASABKAlIABIoCgVkZWx0YRgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RIABIzCgVmaW5hbBgDIAEoCzIiLnJhZ2RvbGwucGx1Z2luLnYxLkV4ZWN1dGVSZXNwb25zZUgAEg8KB25vZGVfaWQYCiABKAlCCQoHcGF5bG9hZCKLAQoFVXNhZ2USEAoIcHJvdmlkZXIYASABKAkSDQoFbW9kZWwYAiABKAkSFAoMaW5wdXRfdG9rZW5zGAMgASgFEhUKDW91dHB1dF90b2tlbnMYBCABKAUSGAoQZW1iZWRkaW5nX3Rva2VucxgFIAEoBRIaChJlc3RpbWF0ZWRfY29zdF91c2QYBiABKAEiRgoIQXJ0aWZhY3QSDAoEa2luZBgBIAEoCRILCgN1cmkYAiABKAkSDAoEZGF0YRgDIAEoDBIRCglzZW5zaXRpdmUYBCABKAgyxAMKDVBsdWdpblJ1bnRpbWUSTQoGSGVhbHRoEiAucmFnZG9sbC5wbHVnaW4udjEuSGVhbHRoUmVxdWVzdBohLnJhZ2RvbGwucGx1Z2luLnYxLkhlYWx0aFJlc3BvbnNlElAKB0V4ZWN1dGUSIS5yYWdkb2xsLnBsdWdpbi52MS5FeGVjdXRlUmVxdWVzdBoiLnJhZ2RvbGwucGx1Z2luLnYxLkV4ZWN1dGVSZXNwb25zZRJbChNFeGVjdXRlU2VydmVyU3RyZWFtEiEucmFnZG9sbC5wbHVnaW4udjEuRXhlY3V0ZVJlcXVlc3QaHy5yYWdkb2xsLnBsdWdpbi52MS5FeGVjdXRlQ2h1bmswARJeChNFeGVjdXRlQ2xpZW50U3RyZWFtEiEucmFnZG9sbC5wbHVnaW4udjEuRXhlY3V0ZVJlcXVlc3QaIi5yYWdkb2xsLnBsdWdpbi52MS5FeGVjdXRlUmVzcG9uc2UoARJVCgtFeGVjdXRlQmlkaRIhLnJhZ2RvbGwucGx1Z2luLnYxLkV4ZWN1dGVSZXF1ZXN0Gh8ucmFnZG9sbC5wbHVnaW4udjEuRXhlY3V0ZUNodW5rKAEwAWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * @generated from message ragdoll.plugin.v1.HealthRequest
 */
export type HealthRequest = Message<"ragdoll.plugin.v1.HealthRequest"> & {
};

/**
 * Describes the message ragdoll.plugin.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export const HealthRequestSchema: GenMessage<HealthRequest> = /*@__PURE__*/
  messageDesc(file_plugin, 0);

/**
 * @generated from message ragdoll.plugin.v1.HealthResponse
 */
export type HealthResponse = Message<"ragdoll.plugin.v1.HealthResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * plugin IDs this server can execute
   *
   * @generated from field: repeated string plugins = 2;
   */
  plugins: string[];

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message ragdoll.plugin.v1.HealthResponse.
 * Use `create(HealthResponseSchema)` to create a new message.
 */
export const HealthResponseSchema: GenMessage<HealthResponse> = /*@__PURE__*/
  messageDesc(file_plugin, 1);

/**
 * Full plugin execution envelope. Fields mirror PluginExecutionInput in the
 * TypeScript plugin-sdk (sans the in-process callbacks like onToken /
 * runPipelineByRef, which can't cross a network boundary).
 *
 * @generated from message ragdoll.plugin.v1.ExecuteRequest
 */
export type ExecuteRequest = Message<"ragdoll.plugin.v1.ExecuteRequest"> & {
  /**
   * plugin id, e.g. "crawl4ai_crawler"
   *
   * @generated from field: string plugin = 1;
   */
  plugin: string;

  /**
   * plugin version, e.g. "0.1.0"
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * DAG node id (for telemetry / cancellation)
   *
   * @generated from field: string node_id = 3;
   */
  nodeId: string;

  /**
   * @generated from field: string tenant_id = 4;
   */
  tenantId: string;

  /**
   * env name (dev/staging/prod)
   *
   * @generated from field: string environment = 5;
   */
  environment: string;

  /**
   * @generated from field: string request_id = 6;
   */
  requestId: string;

  /**
   * resolved config map for the plugin
   *
   * @generated from field: google.protobuf.Struct config = 7;
   */
  config?: JsonObject | undefined;

  /**
   * upstream node outputs feeding this node
   *
   * @generated from field: google.protobuf.Struct inputs = 8;
   */
  inputs?: JsonObject | undefined;

  /**
   * resolved dataset backends + connections
   *
   * @generated from field: google.protobuf.Struct dataset = 9;
   */
  dataset?: JsonObject | undefined;

  /**
   * resolved secret values keyed by name
   *
   * @generated from field: google.protobuf.Struct secrets = 10;
   */
  secrets?: JsonObject | undefined;

  /**
   * soft deadline; 0 = none
   *
   * @generated from field: int32 deadline_ms = 11;
   */
  deadlineMs: number;
};

/**
 * Describes the message ragdoll.plugin.v1.ExecuteRequest.
 * Use `create(ExecuteRequestSchema)` to create a new message.
 */
export const ExecuteRequestSchema: GenMessage<ExecuteRequest> = /*@__PURE__*/
  messageDesc(file_plugin, 2);

/**
 * @generated from message ragdoll.plugin.v1.ExecuteResponse
 */
export type ExecuteResponse = Message<"ragdoll.plugin.v1.ExecuteResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct outputs = 1;
   */
  outputs?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Struct metadata = 2;
   */
  metadata?: JsonObject | undefined;

  /**
   * @generated from field: ragdoll.plugin.v1.Usage usage = 3;
   */
  usage?: Usage | undefined;

  /**
   * @generated from field: repeated ragdoll.plugin.v1.Artifact artifacts = 4;
   */
  artifacts: Artifact[];
};

/**
 * Describes the message ragdoll.plugin.v1.ExecuteResponse.
 * Use `create(ExecuteResponseSchema)` to create a new message.
 */
export const ExecuteResponseSchema: GenMessage<ExecuteResponse> = /*@__PURE__*/
  messageDesc(file_plugin, 3);

/**
 * Streaming envelope. `oneof payload` keeps wire compact — a token frame
 * carries 5 bytes of overhead + the token, not a full ExecuteResponse.
 *
 * @generated from message ragdoll.plugin.v1.ExecuteChunk
 */
export type ExecuteChunk = Message<"ragdoll.plugin.v1.ExecuteChunk"> & {
  /**
   * @generated from oneof ragdoll.plugin.v1.ExecuteChunk.payload
   */
  payload: {
    /**
     * streaming token (LLM, transcript, etc.)
     *
     * @generated from field: string token = 1;
     */
    value: string;
    case: "token";
  } | {
    /**
     * partial outputs update (key/value diff)
     *
     * @generated from field: google.protobuf.Struct delta = 2;
     */
    value: JsonObject;
    case: "delta";
  } | {
    /**
     * completion envelope (last frame on success)
     *
     * @generated from field: ragdoll.plugin.v1.ExecuteResponse final = 3;
     */
    value: ExecuteResponse;
    case: "final";
  } | { case: undefined; value?: undefined };

  /**
   * node attribution; constant across chunks for one call
   *
   * @generated from field: string node_id = 10;
   */
  nodeId: string;
};

/**
 * Describes the message ragdoll.plugin.v1.ExecuteChunk.
 * Use `create(ExecuteChunkSchema)` to create a new message.
 */
export const ExecuteChunkSchema: GenMessage<ExecuteChunk> = /*@__PURE__*/
  messageDesc(file_plugin, 4);

/**
 * @generated from message ragdoll.plugin.v1.Usage
 */
export type Usage = Message<"ragdoll.plugin.v1.Usage"> & {
  /**
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from field: string model = 2;
   */
  model: string;

  /**
   * @generated from field: int32 input_tokens = 3;
   */
  inputTokens: number;

  /**
   * @generated from field: int32 output_tokens = 4;
   */
  outputTokens: number;

  /**
   * @generated from field: int32 embedding_tokens = 5;
   */
  embeddingTokens: number;

  /**
   * @generated from field: double estimated_cost_usd = 6;
   */
  estimatedCostUsd: number;
};

/**
 * Describes the message ragdoll.plugin.v1.Usage.
 * Use `create(UsageSchema)` to create a new message.
 */
export const UsageSchema: GenMessage<Usage> = /*@__PURE__*/
  messageDesc(file_plugin, 5);

/**
 * @generated from message ragdoll.plugin.v1.Artifact
 */
export type Artifact = Message<"ragdoll.plugin.v1.Artifact"> & {
  /**
   * "file" | "log" | "trace" | ...
   *
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: string uri = 2;
   */
  uri: string;

  /**
   * inline bytes (small artifacts); prefer uri for big ones
   *
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  /**
   * @generated from field: bool sensitive = 4;
   */
  sensitive: boolean;
};

/**
 * Describes the message ragdoll.plugin.v1.Artifact.
 * Use `create(ArtifactSchema)` to create a new message.
 */
export const ArtifactSchema: GenMessage<Artifact> = /*@__PURE__*/
  messageDesc(file_plugin, 6);

/**
 * @generated from service ragdoll.plugin.v1.PluginRuntime
 */
export const PluginRuntime: GenService<{
  /**
   * Liveness + capability probe. Returns the plugin IDs this server handles.
   *
   * @generated from rpc ragdoll.plugin.v1.PluginRuntime.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthResponseSchema;
  },
  /**
   * Unary execution — request/response. The HTTP path most plugins take today.
   *
   * @generated from rpc ragdoll.plugin.v1.PluginRuntime.Execute
   */
  execute: {
    methodKind: "unary";
    input: typeof ExecuteRequestSchema;
    output: typeof ExecuteResponseSchema;
  },
  /**
   * Server-streaming — same request, stream of chunks (tokens / partial outputs / final envelope).
   *
   * @generated from rpc ragdoll.plugin.v1.PluginRuntime.ExecuteServerStream
   */
  executeServerStream: {
    methodKind: "server_streaming";
    input: typeof ExecuteRequestSchema;
    output: typeof ExecuteChunkSchema;
  },
  /**
   * Client-streaming — stream of input chunks (multi-modal ingest, large payload), single response.
   *
   * @generated from rpc ragdoll.plugin.v1.PluginRuntime.ExecuteClientStream
   */
  executeClientStream: {
    methodKind: "client_streaming";
    input: typeof ExecuteRequestSchema;
    output: typeof ExecuteResponseSchema;
  },
  /**
   * Bidi — interleaved request/response streams (chat with mid-stream tool-use).
   *
   * @generated from rpc ragdoll.plugin.v1.PluginRuntime.ExecuteBidi
   */
  executeBidi: {
    methodKind: "bidi_streaming";
    input: typeof ExecuteRequestSchema;
    output: typeof ExecuteChunkSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_plugin, 0);

